# Generated by Django 5.2.6 on 2025-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norad_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('norad_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('line1', models.CharField(max_length=80)),
                ('line2', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
